### ISSUE TITLE
Crash when trying to open edit timing point dialog

### ISSUE THREAD

**Issue by willsalt** [willsalt/simple-timetable-editor#320]
Triggered by opening a file, and double-clicking on a timing point or selecting a timing point and pressing "Edit..."

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: key
  Source=mscorlib
  StackTrace:
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Timetabler.CoreData.Helpers.GeneralHelper.GetNewId[T](IEnumerable`1 existingItems) in C:\Users\Will\Source\Repos\simple-timetable-editor\Timetabler.CoreData\Helpers\GeneralHelper.cs:line 28
   at Timetabler.MainForm.EditTrain(String trainId) in C:\Users\Will\Source\Repos\simple-timetable-editor\Timetabler\MainForm.cs:line 458
   at Timetabler.MainForm.CellDoubleClicked(DataGridView dgv, DataGridViewCellEventArgs e) in C:\Users\Will\Source\Repos\simple-timetable-editor\Timetabler\MainForm.cs:line 552
   at Timetabler.MainForm.DgvDown_CellContentDoubleClick(Object sender, DataGridViewCellEventArgs e) in C:\Users\Will\Source\Repos\simple-timetable-editor\Timetabler\MainForm.cs:line 513
   at System.Windows.Forms.DataGridView.OnCellContentDoubleClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCommonCellContentClick(Int32 columnIndex, Int32 rowIndex, Boolean doubleClick)
   at System.Windows.Forms.DataGridViewCell.OnMouseUpInternal(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellMouseUp(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Timetabler.Program.Main(String[] args) in C:\Users\Will\Source\Repos\simple-timetable-editor\Timetabler\Program.cs:line 27

  This exception was originally thrown at this call stack:
    [External Code]
    Timetabler.CoreData.Helpers.GeneralHelper.GetNewId<T>(System.Collections.Generic.IEnumerable<T>) in GeneralHelper.cs
    Timetabler.MainForm.EditTrain(string) in MainForm.cs
    Timetabler.MainForm.CellDoubleClicked(System.Windows.Forms.DataGridView, System.Windows.Forms.DataGridViewCellEventArgs) in MainForm.cs
    Timetabler.MainForm.DgvDown_CellContentDoubleClick(object, System.Windows.Forms.DataGridViewCellEventArgs) in MainForm.cs
    [External Code]
    Timetabler.Program.Main(string[]) in Program.cs
```

**Comment by willsalt** [comment]
There are three separate issues here

1. The actual point where the exception is being thrown, caused by `GeneralHelper.GetNewId<T>(IEnumerable<T> existingItems)` assuming that all members of `existingItems` will have a non-null `Id` property
1. The fact that when a train with a null `Id` property is loaded, the loader does not notice and generate a new ID for it
1. The fact that somehow, trains with null `Id` properties were created by the program, probably due to the train-copying functionality.

**Comment by willsalt** [comment]
This issue will cover point 1 above.  Point 2 is covered by issue #321 and Point 3 is covered by issue #322.
